language: ruby
script: rspec
bundler_args: --without development
before_install:
  - 'test "$CQL_ENABLE_AUTH" = "1" && sudo perl -pi -e "s/(?<=authenticator: )AllowAllAuthenticator/PasswordAuthenticator/" /usr/local/cassandra/conf/cassandra.yaml && echo "Authentication enabled" || echo "Authentication disabled"'
  - 'test "$CQL_ENABLE_AUTH" = "1" && sudo service cassandra restart || :'
env:
  matrix:
    - CQL_ENABLE_AUTH=1
    - CQL_ENABLE_AUTH=0
services:
  - cassandra
  - redis-server
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - jruby
  - rbx-2
jdk:
  - openjdk7
matrix:
  exclude:
    - rvm: 1.9.3
      jdk: openjdk7
      env: CQL_ENABLE_AUTH=1
    - rvm: 2.1.1
      jdk: openjdk7
      env: CQL_ENABLE_AUTH=1
    - rvm: jruby
      jdk: openjdk7
      env: CQL_ENABLE_AUTH=1
    - rvm: rbx-2
      jdk: openjdk7
      env: CQL_ENABLE_AUTH=1
